const $=s=>document.querySelector(s),plan=window.ATLAS_PLAN,cfg=window.ATLAS_CONFIG;
let records=[],session=null,view='today',week=0,busy=false,loadFailed=false;
try{session=JSON.parse(localStorage.getItem('atlas-session')||'null')}catch{}
const configured=()=>/^https:\/\/[^/]+\.supabase\.co\/?$/.test(cfg.supabaseUrl)&&!!cfg.supabaseKey;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=x=>new Date(x+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'});
const now=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const record=d=>records.find(r=>r.workout_date===d);
const pace=r=>{if(!r?.km||!r?.minutes)return '—';let s=Math.round(r.minutes/r.km*60);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}/km`};
function keepSession(s){session=s;if(s)localStorage.setItem('atlas-session',JSON.stringify(s));else localStorage.removeItem('atlas-session');}
async function request(path,options={},token=false){
 if(token){if(!session)throw Error('Entre para salvar seus treinos.');if(session.expires_at<Date.now()/1000+60){const r=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});keepSession({...r,expires_at:Date.now()/1000+r.expires_in});}}
 const res=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+path,{...options,headers:{apikey:cfg.supabaseKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+session.access_token}:{}),...options.headers}});
 const body=await res.text();let data;try{data=body?JSON.parse(body):null}catch{throw Error('Resposta inesperada do servidor.');}if(!res.ok)throw Error(data?.msg||data?.message||data?.error_description||'Não foi possível concluir. Tente novamente.');return data;
}
async function load(){if(!configured()){notice('Calendário disponível. O login ainda precisa ser configurado para sincronizar os registros.');render();return;}if(!session){notice('Entre para salvar e sincronizar seus treinos.');render();return;}notice('Buscando seus registros…');try{records=await request('/rest/v1/atlas_records?select=*&order=workout_date.asc',{},true);loadFailed=false;notice('Registros sincronizados.');}catch(e){loadFailed=true;notice('Não foi possível carregar seus registros. '+e.message);}render();}
function notice(t){$('#notice').textContent=t;$('#account').textContent=session?'Sair':'Entrar';}
function workout(p){let r=record(p.date);return `<article class="card"><span class="tag">${esc(dateLabel(p.date))} · ${esc(p.type)}</span><h2>${p.type==='Descanso'?'Recuperar também é treino':p.type.includes('Força')?'Manter a força':p.type.includes('Avaliação')?'Conhecer o ponto de partida':p.type.includes('Longão')?'Construir resistência':'Corrida do dia'}</h2><div class="distance">${p.km||'—'} <small>${p.km?'km previstos':'sem corrida'}</small></div><p>${esc(p.execution)}</p>${p.gym!=='—'?`<p><strong>${esc(p.gym)}</strong></p>`:''}<p class="muted">${esc(p.condition)}</p>${r?`<p class="status">${esc(r.status)} · ${r.km??'—'} km · ${pace(r)}</p>`:''}<button class="primary" data-record="${p.date}">${r?'Editar registro':'Registrar treino'}</button></article>`;}
function render(){
 const current=plan.find(p=>p.date===now())||plan.find(p=>p.date>now())||plan.at(-1);
 document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 let html='';
 if(view==='today')html=workout(current)+`<div class="card"><h3>Como usar este bloco</h3><p class="muted">Corra em esforço confortável. Os longões são limites condicionais, não tarefas para cumprir a qualquer custo.</p><button data-view="guide" class="secondary">Ver regras de ajuste</button></div>`;
 if(view==='calendar'){let days=plan.slice(week*7,week*7+7);html='<div class="week" aria-label="Selecionar semana">'+Array.from({length:6},(_,i)=>`<button data-week="${i}" class="${i===week?'selected':''}">Semana ${i+1}</button>`).join('')+'</div>'+days.map(p=>`<button class="workout" data-detail="${p.date}"><div class="row"><strong>${esc(dateLabel(p.date))}</strong><span>${p.km?p.km+' km':p.type}</span></div><small>${esc(p.type)}${record(p.date)?' · '+esc(record(p.date).status):''}</small></button>`).join('')+'<div id="detail"></div>';}
 if(view==='progress'){let done=records.filter(r=>r.status!=='não feito'),km=done.reduce((s,r)=>s+Number(r.km||0),0),mins=done.reduce((s,r)=>s+Number(r.minutes||0),0),weekly=Array.from({length:6},(_,i)=>records.filter(r=>plan.slice(i*7,i*7+7).some(p=>p.date===r.workout_date)&&r.status!=='não feito').reduce((s,r)=>s+Number(r.km||0),0)),max=Math.max(1,...weekly);html=`<h2>Seu ritmo de evolução</h2><div class="metrics"><div class="metric"><strong>${done.length}</strong><span>treinos feitos</span></div><div class="metric"><strong>${km.toFixed(1)}</strong><span>km registrados</span></div><div class="metric"><strong>${Math.round(mins)}</strong><span>minutos</span></div></div><div class="card"><h3>Distância por semana</h3><div class="bars" aria-label="${weekly.map((n,i)=>'Semana '+(i+1)+': '+n+' km').join('; ')}">${weekly.map((n,i)=>`<div class="bar" style="height:${Math.max(3,n/max*100)}%" title="${n} km"><span>S${i+1}</span></div>`).join('')}</div></div>${!records.length?'<p class="muted">Os resultados aparecem depois do primeiro registro sincronizado.</p>':''}${records.slice().reverse().map(r=>`<div class="card"><div class="row"><h3>${esc(dateLabel(r.workout_date))}</h3><span class="status">${esc(r.status)}</span></div><p>${r.km??'—'} km · ${pace(r)} · esforço ${r.effort??'—'}/10</p><p class="muted">Dor ${r.pain??'—'}/10 · ${esc(r.recovery||'Recuperação pendente')}</p><p>${esc(r.notes)}</p><button data-record="${r.workout_date}" class="secondary">Editar</button></div>`).join('')}<button id="export" class="primary">Baixar dados para análise</button><button id="share" class="secondary">Compartilhar resumo</button><button id="reload" class="secondary">Atualizar registros</button>`;}
 if(view==='guide')html=`<h2>Guia do bloco</h2>`+[
 ['Avaliação inicial de 5 km','Caminhe 5–10 min, corra até 5 km em esforço 3–4/10 e caminhe 5 min ao final. Pode parar antes ou caminhar. Não é um teste máximo. Registre tempo, esforço e recuperação no dia seguinte.'],
 ['Quando reduzir','Se os 5 km exigirem esforço acima de 5/10, pausas frequentes ou recuperação acima de 48 h, use três sessões semanais de 25–35 min corrida/caminhada e longão de 5–6 km. Não execute a progressão automaticamente.'],
 ['Ritmo e longões','Leve: esforço 3–4/10, conversando em frases completas. 7:30–8:30/km é só referência; pode ser mais lento. Longões 6 → 8 → 10 → até 12 km só com boa recuperação em 24–48 h. Pode alternar 4 min correndo e 1 min caminhando. Não compense treino perdido.'],
 ['Musculação A','Supino 2×8–12, remada 2×8–12, agachamento ou leg press 2×8, flexora 2×10, panturrilha 2×12. Cerca de 40–50 min. Deixe 3 repetições em reserva. Use exercícios conhecidos.'],
 ['Musculação B','Puxada 2×8–12, supino inclinado 2×8–12, elevação lateral 2×12, bíceps e tríceps 1–2×10, prancha 2×30–45 s. Cerca de 35–45 min. Sem falha. Reduza pernas se atrapalharem a corrida. Boxe pausado.'],
 ['Rua, esteira e tiros','Esteira a 0–1%, sem apoiar nas barras. Caminhe nas subidas e controle descidas. Prefira trajetos planos nos longões. Sem tiros intensos neste bloco. Trechos controlados só se o esforço permitir.'],
 ['Decisão em 8 de novembro','10–12 km confortáveis ajudam a avaliar, mas não comprovam preparo para 21 km. Se houver dor, fadiga persistente ou longão difícil, adie a meia. 38 dias é um prazo curto; vale revisar com um treinador presencial.'],
 ['Meta de 2h30','Exige aproximadamente 7:07/km contando caminhadas e paradas. Só considerar se os trechos próximos de 7:00–7:10 forem controlados e os longões bem tolerados. Completar com saúde prevalece sobre o relógio.'],
 ['Água e alimentação','Em treinos acima de 75 min, teste carboidrato começando perto de 30 g/h. Para a prova, 30–60 g/h conforme tolerância e rótulo. Beba conforme sede e calor, sem forçar litros. Refeição habitual rica em carboidrato 2–3 h antes. Não estreie gel na prova.'],
 ['Dor e sinais de alerta','Dor localizada que aumenta ou altera a passada: pare. Dor persistente merece avaliação. Dor no peito, desmaio ou falta de ar incomum: atendimento urgente.'],
 ['Compartilhar para análise','Em Evolução, baixe os dados ou compartilhe o resumo e envie nesta conversa. Isso não envia nada automaticamente ao ChatGPT. Os registros ficam na sua conta e só você os acessa.']
 ].map(([t,b])=>`<details><summary>${t}</summary><p>${b}</p></details>`).join('')+`<p class="muted">Referências: <a href="https://www.baa.org/races/boston-half/info-for-athletes/boston-half-training/">BAA</a>, <a href="https://www.nhs.uk/better-health/get-active/get-running-with-couch-to-5k/couch-to-5k-running-plan/">NHS</a>, <a href="https://www.ausport.gov.au/ais/nutrition/supplements/group_a/sports-foods2/sports-gels/how-and-when-do-i-use-it/">AIS</a>. Plano sugerido e condicionado à resposta individual.</p>`;
 $('#content').innerHTML=html;
}
function openRecord(d){if(!configured()){notice('O login precisa ser configurado antes de registrar. Consulte as instruções entregues com o app.');return;}if(!session){$('#authDialog').showModal();return;}if(loadFailed){notice('Atualize os registros antes de editar, para evitar sobrescrever dados que não carregaram.');return;}let f=$('#recordForm'),r=record(d)||{};f.reset();f.elements.date.value=d;for(let k of ['status','km','minutes','effort','pain','recovery','notes'])if(r[k]!=null)f.elements[k].value=r[k];$('#recordTitle').textContent='Treino · '+dateLabel(d);$('#saveError').textContent='';$('#recordDialog').showModal();}
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();}if(b.dataset.week){week=Number(b.dataset.week);render();}if(b.dataset.detail){$('#detail').innerHTML=workout(plan.find(p=>p.date===b.dataset.detail));$('#detail').scrollIntoView({behavior:'smooth',block:'start'});}if(b.dataset.record)openRecord(b.dataset.record);if(b.dataset.close)$('#'+b.dataset.close).close();if(b.id==='reload')load();if(b.id==='export'){if(!session||loadFailed){notice('Entre e carregue seus registros antes de exportar.');return;}download('atlas21-dados.json',JSON.stringify({project:'Atlas 21K',exportedAt:new Date().toISOString(),goal:{km:21.1,minutes:150,date:'2026-11-15'},plan,records:records.map(({user_id,...r})=>r)},null,2),'application/json');}if(b.id==='share'){let text=summary();if(navigator.share){try{await navigator.share({title:'Atlas 21K — treinos',text})}catch(e){if(e.name!=='AbortError')download('atlas21-resumo.txt',text,'text/plain');}}else download('atlas21-resumo.txt',text,'text/plain');}});
function download(name,text,type){let u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function summary(){return 'Projeto Atlas 21K | meta 15/11/2026, até 2h30\n'+(records.length?records.map(r=>`${r.workout_date}: ${r.status}; ${r.km??'—'} km; ${r.minutes??'—'} min; ${pace(r)}; esforço ${r.effort??'—'}/10; dor ${r.pain??'—'}/10; recuperação ${r.recovery||'pendente'}; ${r.notes}`).join('\n'):'Ainda sem registros.')+'\nAnalise minha evolução e recuperação. Não presuma preparo para os 21 km apenas pelo pace.';}
$('#recordForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;let f=e.target;if(!f.reportValidity())return;let data=Object.fromEntries(new FormData(f));if(['km','minutes'].some(k=>data[k]!==''&&Number(data[k])<=0)&&data.status!=='não feito'&&plan.find(p=>p.date===data.date).km>0){$('#saveError').textContent='Para corrida realizada, distância e tempo informados precisam ser positivos.';return;}busy=true;let b=f.querySelector('[type=submit]');b.disabled=true;$('#saveError').textContent='';try{const row={user_id:session.user.id,workout_date:data.date,status:data.status,recovery:data.recovery,notes:data.notes,updated_at:new Date().toISOString()};for(let k of ['km','minutes','effort','pain'])row[k]=data[k]===''?null:Number(data[k]);await request('/rest/v1/atlas_records?on_conflict=user_id,workout_date',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(row)},true);records=records.filter(r=>r.workout_date!==row.workout_date).concat(row).sort((a,b)=>a.workout_date.localeCompare(b.workout_date));$('#recordDialog').close();notice('Treino salvo e sincronizado.');render();}catch(e){$('#saveError').textContent='Não salvou. Seus campos foram mantidos. '+e.message;}finally{busy=false;b.disabled=false;}});
$('#account').onclick=async()=>{if(session){try{await request('/auth/v1/logout',{method:'POST'},true)}catch{}keepSession(null);records=[];notice('Você saiu da conta.');render();}else if(configured())$('#authDialog').showModal();else notice('Login ainda não configurado. O calendário e guia já podem ser consultados.');};
async function auth(signup=false){const f=$('#authForm');if(!f.reportValidity()||busy)return;busy=true;f.querySelectorAll('button').forEach(b=>b.disabled=true);$('#authError').textContent='Conectando…';try{let data=Object.fromEntries(new FormData(f));let r=await request(signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify(data)});if(r.access_token){keepSession({...r,expires_at:Date.now()/1000+r.expires_in});f.reset();$('#authDialog').close();await load();}else $('#authError').textContent='Confira seu e-mail para confirmar a conta. Depois volte e entre.';}catch(e){$('#authError').textContent=e.message;}finally{busy=false;f.querySelectorAll('button').forEach(b=>b.disabled=false);}}
$('#authForm').onsubmit=e=>{e.preventDefault();auth()};$('#signup').onclick=()=>auth(true);
render();load();
