import {parsePlan} from './importer.js';
import {consumeAuthCallback} from './auth-callback.js';
const $=s=>document.querySelector(s),cfg=window.ATLAS_CONFIG;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,plans=[],records=[],profile=null,admin=false,view='today',active=null,draft=null,athletes=[],demo=false,loaded=false,busy=false;
try{session=JSON.parse(localStorage.getItem('atlas-session')||'null')}catch{}
const configured=()=>{if(!/^https:\/\/[^/]+\.supabase\.co\/?$/.test(cfg.supabaseUrl))return false;if(cfg.supabaseKey?.startsWith('sb_publishable_'))return true;try{return JSON.parse(atob(cfg.supabaseKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='anon';}catch{return false;}};
function keepSession(s){session=s;if(s)localStorage.setItem('atlas-session',JSON.stringify(s));else localStorage.removeItem('atlas-session');}
let refresh=null;
async function request(path,options={},token=true){
 if(!configured())throw Error('Configure a URL e a chave pública do Supabase.');
 if(token){if(!session)throw Error('Entre na sua conta.');if(session.expires_at<Date.now()/1000+60){if(!refresh)refresh=request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})},false).then(r=>keepSession({...r,expires_at:Date.now()/1000+r.expires_in})).finally(()=>refresh=null);await refresh;}}
 const res=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+path,{...options,headers:{apikey:cfg.supabaseKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+session.access_token}:{}),...options.headers}});
 const text=await res.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('Resposta inesperada do servidor.');}if(!res.ok)throw Error(data?.msg||data?.message||data?.error_description||'Falha no servidor.');return data;
}
const post=(path,data,headers={})=>request(path,{method:'POST',headers,body:JSON.stringify(data)});
function notice(t){$('#notice').textContent=t;$('#account').textContent=session?'Sair':'Entrar';}
const current=()=>plans.find(p=>p.id===active);
const rec=id=>records.find(r=>r.plan_id===active&&r.session_id===id);
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});
async function load(){loaded=false;try{
 if(!session){render();return;}
 const roles=await request('/rest/v1/atlas_admins?select=user_id');admin=roles.some(r=>r.user_id===session.user.id);
 let ps=await request('/rest/v1/atlas_profiles?select=*');profile=ps.find(p=>p.user_id===session.user.id);
 if(!profile){await post('/rest/v1/atlas_profiles',{user_id:session.user.id,name:admin?'Administrador':'Atleta',available_days:[]});ps=await request('/rest/v1/atlas_profiles?select=*');profile=ps.find(p=>p.user_id===session.user.id);}
 if(admin){athletes=ps.filter(p=>!p.is_admin);plans=[];records=[];view='admin';}
 else{plans=await request('/rest/v1/atlas_plans?select=*,atlas_sessions(*)&order=created_at.desc');plans=plans.map(p=>({...p,sessions:p.atlas_sessions.sort((a,b)=>a.date.localeCompare(b.date))}));records=await request('/rest/v1/atlas_activity_records?select=*');if(!plans.some(p=>p.id===active))active=plans[0]?.id;}
 loaded=true;notice(admin?'Área de administração. Use outra conta para seus treinos.':'Dados sincronizados.');render();
 }catch(e){notice('Não foi possível carregar os dados. '+e.message);render();}}
function workout(s){const r=rec(s.id);return `<article class="card"><span class="tag">${esc(dateLabel(s.date))} · ${esc(s.type)}</span><h2>${esc(s.type)}</h2><div class="distance">${s.km??'—'} <small>km previstos</small></div><p>${esc(s.description)}</p><p>${esc(s.intensity)} ${s.minutes? '· '+s.minutes+' min':''}</p><p>${esc(s.gym)}</p><p class="muted">${esc(s.notes)}</p>${r?`<p class="status">${esc(r.status)} · ${r.km??'—'} km · ${r.minutes??'—'} min</p>`:''}<button class="primary" data-record="${esc(s.id)}">${r?'Editar registro':'Registrar atividade'}</button></article>`;}
function render(){
 $('#sync').hidden=!session;
 $('#planSelect').hidden=admin||!plans.length;$('#planSelect').innerHTML=plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('#planSelect').value=active||'';
 $('nav').hidden=admin;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const p=current();$('#goal').textContent=p?`${p.goal_km??'—'} km · ${p.goal_minutes??'—'} min${p.goal_date?' · '+dateLabel(p.goal_date):''}`:'Seu plano, seu ritmo';
 let html='';
 if(admin){html=`<h2>Importar um plano</h2><p>Planos anteriores são preservados. As datas importadas não são remanejadas.</p><a href="modelo-plano.csv" download>Baixar modelo CSV</a> · <a href="IMPORTACAO.md" target="_blank">Formato e prompt GPT</a><label>Atleta<select id="athlete"><option value="">Selecione um atleta</option>${athletes.map(a=>`<option value="${esc(a.user_id)}">${esc(a.name)} · ${esc(a.user_id)}</option>`).join('')}</select></label><label>Planilha CSV UTF-8<input id="importFile" type="file" accept=".csv,text/csv"></label><div id="preview"></div>`;}
 else if(!session&&!demo){html='<article class="card"><h2>Seu próximo passo começa aqui.</h2><p>Entre ou crie sua conta para acessar seus planos e registrar atividades.</p><button id="login" class="primary">Entrar / criar conta</button><button id="demo" class="secondary">Explorar plano anterior em demonstração</button><p class="muted">A demonstração mantém dados apenas em memória. A prova antiga não está confirmada.</p></article>';}
 else if(view==='profile'){html=`<h2>Meu perfil</h2><form id="profileForm"><label>Nome<input name="name" maxlength="120" required value="${esc(profile?.name||'Atleta demonstração')}"></label><fieldset><legend>Dias disponíveis</legend>${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((d,i)=>`<label><input type="checkbox" name="days" value="${i}" ${(profile?.available_days||[]).includes(i)?'checked':''}> ${d}</label>`).join('')}</fieldset><p>Preferências para futuros planos. Não mudam as datas já importadas.</p><button class="primary">Salvar perfil</button><p id="profileError" role="status"></p></form>`;}
 else if(!p){html='<div class="card"><h2>Nenhum plano atribuído</h2><p>Configure seu perfil. O administrador poderá vincular seu plano à sua conta.</p></div>';}
 else if(view==='today'){const today=new Date().toLocaleDateString('en-CA');const ss=p.sessions.filter(s=>s.date===today);html=(ss.length?ss:[p.sessions.find(s=>s.date>today)||p.sessions.at(-1)]).map(workout).join('');}
 else if(view==='calendar')html='<h2>Calendário completo</h2>'+p.sessions.map(workout).join('');
 else if(view==='guide')html='<h2>Guia do plano</h2>'+p.guide.map(g=>`<details><summary>${esc(g.tema)}</summary><p>${esc(g.orientacao)}</p></details>`).join('');
 else if(view==='progress'){const rs=records.filter(r=>r.plan_id===active),done=rs.filter(r=>r.status!=='não feito');html=`<h2>Minha evolução</h2><div class="metrics"><div class="metric"><strong>${done.length}/${p.sessions.length}</strong><span>sessões realizadas</span></div><div class="metric"><strong>${done.reduce((n,r)=>n+(r.km||0),0).toFixed(1)}</strong><span>km reais</span></div><div class="metric"><strong>${done.reduce((n,r)=>n+(r.minutes||0),0).toFixed(0)}</strong><span>minutos reais</span></div></div>${rs.map(r=>`<article class="card"><h3>${esc(p.sessions.find(s=>s.id===r.session_id)?.type)} · ${esc(r.status)}</h3><p>${r.km??'—'} km · ${r.minutes??'—'} min · esforço ${r.effort??'—'}/10 · dor ${r.pain??'—'}/10</p><p>${esc(r.recovery)} · ${esc(r.notes)}</p><button data-record="${esc(r.session_id)}">Editar</button></article>`).join('')}<button id="export" class="primary">Exportar plano e registros para GPT</button><button id="reload" class="secondary">Sincronizar novamente</button>`;}
 $('#content').innerHTML=html;
}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function openRecord(id){if(!demo&&(!loaded||!session)){notice('Entre e sincronize antes de editar.');return;}const f=$('#recordForm'),r=rec(id)||{};f.reset();f.elements.session_id.value=id;for(const k of ['status','km','minutes','effort','pain','recovery','notes'])if(r[k]!=null)f.elements[k].value=r[k];$('#saveError').textContent='';$('#recordTitle').textContent='Registrar · '+current().sessions.find(s=>s.id===id).type;$('#recordDialog').showModal();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.view){view=b.dataset.view;render();}if(b.dataset.close)$('#'+b.dataset.close).close();if(b.dataset.record)openRecord(b.dataset.record);
 if(b.id==='login')$('#account').click();if(b.id==='reload'||b.id==='sync')await load();
 if(b.id==='demo'){demo=true;profile=null;plans=[{id:'legacy',name:'Plano anterior · referência, prova não confirmada',goal_km:21.1,goal_minutes:150,goal_date:'2026-11-15',guide:window.ATLAS_LEGACY_GUIDE,sessions:window.ATLAS_PLAN.map((s,i)=>({id:'legacy-'+i,date:s.date,type:s.type,km:s.km,description:s.execution,gym:s.gym,notes:s.condition}))}];active='legacy';records=[];notice('DEMONSTRAÇÃO — dados temporários em memória, sem sincronização. Prova não confirmada.');render();}
 if(b.id==='export'){if(!demo&&!loaded)return;download('atlas-run-dados.json',JSON.stringify({app:'Atlas Run',demo,exported_at:new Date().toISOString(),plans:plans.map(({user_id,atlas_sessions,...p})=>({...p,sessions:p.sessions.map(({user_id,plan_id,...s})=>s)})),records:records.map(({user_id,...r})=>r)},null,2));}
 if(b.id==='confirmImport'&&!busy){const athlete=$('#athlete').value;if(!athlete||!draft){notice('Selecione um atleta e carregue um arquivo válido.');return;}busy=true;b.disabled=true;try{await post('/rest/v1/rpc/atlas_import_plan',{athlete,document:draft});draft=null;$('#preview').textContent='Plano importado com sucesso. O atleta verá o plano ao sincronizar.';$('#importFile').value='';}catch(e){notice('Importação não salva. '+e.message);}finally{busy=false;b.disabled=false;}}
});
document.addEventListener('change',async e=>{if(e.target.id==='planSelect'){active=e.target.value;render();}if(e.target.id==='importFile'){draft=null;$('#preview').textContent='';try{const file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('Limite de arquivo: 2 MB.');draft=parsePlan(await file.text());$('#preview').innerHTML=`<h2>Prévia: ${esc(draft.name)}</h2><p>Meta: ${draft.goal_km??'—'} km · ${draft.goal_minutes??'—'} min · ${esc(draft.goal_date)}</p><p>${draft.sessions.length} sessões</p>${draft.sessions.map(s=>`<article class="card"><h3>${esc(s.date)} · ${esc(s.id)} · ${esc(s.type)}</h3><p>${s.km??'—'} km · ${s.minutes??'—'} min · ${esc(s.intensity)}</p><p>${esc(s.description)}</p><p>${esc(s.gym)} · ${esc(s.notes)}</p></article>`).join('')}<h3>Guia completo</h3>${draft.guide.map(g=>`<p><strong>${esc(g.tema)}</strong>: ${esc(g.orientacao)}</p>`).join('')}<button id="confirmImport" class="primary">Confirmar importação para o atleta selecionado</button>`;}catch(e){$('#preview').textContent=e.message;}}});
$('#recordForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=e.target,data=Object.fromEntries(new FormData(f)),row={user_id:session?.user.id,plan_id:active,session_id:data.session_id,status:data.status,recovery:data.recovery,notes:data.notes,updated_at:new Date().toISOString()};for(const k of ['km','minutes','effort','pain'])row[k]=data[k]===''?null:Number(data[k]);busy=true;const b=f.querySelector('[type=submit]');b.disabled=true;try{if(!demo)await post('/rest/v1/atlas_activity_records?on_conflict=user_id,plan_id,session_id',row,{Prefer:'resolution=merge-duplicates'});records=records.filter(r=>!(r.plan_id===active&&r.session_id===row.session_id)).concat(row);$('#recordDialog').close();notice(demo?'Registro temporário na demonstração. Não foi sincronizado.':'Atividade salva e sincronizada.');render();}catch(e){$('#saveError').textContent='Não salvou. Seus campos foram mantidos. '+e.message;}finally{busy=false;b.disabled=false;}};
document.addEventListener('submit',async e=>{if(e.target.id!=='profileForm')return;e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{const data={name:f.elements.name.value,available_days:new FormData(f).getAll('days').map(Number)};if(!demo)await request('/rest/v1/atlas_profiles?user_id=eq.'+session.user.id,{method:'PATCH',body:JSON.stringify(data)});profile={...profile,...data};$('#profileError').textContent=demo?'Perfil temporário na demonstração.':'Perfil salvo.';}catch(e){$('#profileError').textContent=e.message;}finally{b.disabled=false;}});
$('#account').onclick=async()=>{if(busy)return;if(session){try{await request('/auth/v1/logout',{method:'POST'})}catch{}keepSession(null);admin=false;demo=false;loaded=false;plans=[];records=[];profile=null;view='today';draft=null;notice('Você saiu.');render();}else{if(!configured()){notice('Supabase não configurado. Login real indisponível; explore a demonstração.');return;}$('#authDialog').showModal();}};
async function auth(signup=false){const f=$('#authForm');if(!f.reportValidity()||busy)return;busy=true;f.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await request(signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))},false);if(r.access_token){keepSession({...r,expires_at:Date.now()/1000+r.expires_in});demo=false;plans=[];records=[];f.reset();$('#authDialog').close();await load();}else $('#authError').textContent='Confirme seu e-mail e depois entre.';}catch(e){$('#authError').textContent=e.message;}finally{busy=false;f.querySelectorAll('button').forEach(b=>b.disabled=false);}}
$('#authForm').onsubmit=e=>{e.preventDefault();auth()};$('#signup').onclick=()=>auth(true);
notice(configured()?'Entre para acessar seus planos.':'Supabase não configurado. Demonstração disponível, sem persistência.');render();
async function initialize(){try{const confirmed=await consumeAuthCallback(window.location,window.history,request);if(confirmed)keepSession(confirmed);if(session)await load();}catch(e){notice('Não foi possível confirmar seu acesso. '+e.message);}}
initialize();
