import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {parsePlan} from '../importer.js';

test('management PostgreSQL: scoped coaches, drafts, versions, immutable records and optimistic concurrency', async () => {
 const db = new PGlite();
 const ids = Array.from({length: 5}, (_, i) => `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`);
 const [A, B, OWNER, C, D] = ids;
 const doc = parsePlan(readFileSync(new URL('../modelo-plano.csv', import.meta.url), 'utf8'));
 const actor = async (id, role = 'authenticated') => {await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id || '']); await db.exec('set role ' + role);};
 const save = async (athlete, document = doc, id = null, revision = null, base = null) => (await db.query('select public.atlas_save_draft($1,$2,$3::jsonb,$4,$5) as d', [id, athlete, JSON.stringify(document), revision, base])).rows[0].d;
 const publish = async d => (await db.query('select public.atlas_publish_draft($1,$2) as id', [d.id, d.revision])).rows[0].id;
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;`);
  await db.exec(readFileSync(new URL('../schema-v2.sql', import.meta.url), 'utf8'));
  for (const id of ids) {await db.query('insert into auth.users values($1)', [id]); await db.query('insert into public.atlas_profiles(user_id,name) values($1,$2)', [id, 'Pessoa ' + id.slice(-1)]);}
  await db.query('insert into public.atlas_admins values($1)', [OWNER]);
  // Upgrade must preserve the already-published plan and its activity.
  await actor(OWNER);
  const original = (await db.query('select public.atlas_import_plan($1,$2::jsonb) as id', [A, JSON.stringify(doc)])).rows[0].id;
  await actor(A); await db.query("insert into public.atlas_activity_records(user_id,plan_id,session_id,status,km) values($1,$2,'sessao-001','feito',3)", [A, original]);
  await db.exec('reset role'); await db.exec(readFileSync(new URL('../schema-v3.sql', import.meta.url), 'utf8'));
  await actor(OWNER);
  await db.query('insert into public.atlas_coaches(user_id) values($1),($2)', [C, D]);
  await assert.rejects(db.query('insert into public.atlas_coaches(user_id) values($1)', [A]), /conta separada/);
  await db.query('insert into public.atlas_coach_athletes(coach_id,athlete_id) values($1,$2),($3,$4)', [C, A, D, B]);
  await assert.rejects(db.query('insert into public.atlas_coach_athletes(coach_id,athlete_id) values($1,$2)', [C, D]), /conta de atleta/);
  await actor(A);
  assert.equal((await db.query('select public.atlas_access_context() as c')).rows[0].c.role, 'athlete');
  await assert.rejects(db.query('insert into public.atlas_coaches(user_id) values($1)', [A]), /Somente o dono/);
  await assert.rejects(db.query('update public.atlas_profiles set is_admin=true'), /permission denied/);
  await assert.rejects(save(A), /não autorizado/);
  assert.equal((await db.query('select * from public.atlas_plan_drafts')).rows.length, 0);
  await actor(C);
  assert.equal((await db.query('select public.atlas_access_context() as c')).rows[0].c.role, 'coach');
  assert.deepEqual(new Set((await db.query('select user_id from public.atlas_profiles')).rows.map(p => p.user_id)), new Set([A, C]));
  assert.equal((await db.query('select * from public.atlas_activity_records')).rows.length, 0);
  await assert.rejects(save(B), /não autorizado/);
  await assert.rejects(db.query("insert into public.atlas_plans(user_id,name,guide) values($1,'Bypass','[{\"tema\":\"x\",\"orientacao\":\"y\"}]')", [A]), /permission denied/);
  await assert.rejects(db.query("update public.atlas_sessions set description='Bypass'"), /permission denied/);
  await assert.rejects(db.query("insert into public.atlas_activity_records(user_id,plan_id,session_id,status) values($1,$2,'sessao-001','feito')", [C,original]), /row-level security/);
  await assert.rejects(db.query('insert into public.atlas_coach_athletes(coach_id,athlete_id) values($1,$2)', [C, B]), /Somente o dono/);
  await assert.rejects(db.query('update public.atlas_plans set state=\'archived\''), /permission denied/);
  const before = (await db.query('select count(*)::int as n from public.atlas_plan_drafts')).rows[0].n;
  await assert.rejects(save(A, {...doc, sessions: [doc.sessions[0], doc.sessions[0]]}), /repetido/);
  assert.equal((await db.query('select count(*)::int as n from public.atlas_plan_drafts')).rows[0].n, before);
  const draft = await save(A);
  await actor(A); assert.equal((await db.query('select * from public.atlas_plan_drafts')).rows.length, 0); assert.equal((await db.query('select * from public.atlas_plans')).rows.length, 1);
  await actor(D); assert.equal((await db.query('select * from public.atlas_plan_drafts')).rows.length, 0); await assert.rejects(publish(draft), /não autorizado/);
  await actor(C);
  const edited = await save(A, {...doc, name: 'Editado'}, draft.id, draft.revision);
  assert.equal(edited.revision, 2);
  await assert.rejects(save(A, doc, draft.id, 1), /Conflito/);
  await assert.rejects(publish(draft), /Conflito/);
  await assert.rejects(db.query('select public.atlas_publish_draft($1,null)', [edited.id]), /Conflito/);
  await assert.rejects(db.query("update public.atlas_plan_drafts set state='published' where id=$1", [edited.id]), /permission denied/);
  const newPlan = await publish(edited);
  await assert.rejects(publish(edited), /Conflito/);
  await assert.rejects(save(A, doc, draft.id, 3), /Conflito/);
  const revision = await save(A, {...doc, name: 'Revisão'}, null, null, original);
  const revisionPlan = await publish(revision);
  const old = (await db.query('select * from public.atlas_plans where id=$1', [original])).rows[0];
  const latest = (await db.query('select * from public.atlas_plans where id=$1', [revisionPlan])).rows[0];
  assert.equal(old.state, 'archived'); assert.equal(latest.version, 2); assert.equal(latest.previous_plan_id, original);
  assert.equal((await db.query('select count(*)::int as n from public.atlas_sessions where plan_id=$1', [original])).rows[0].n, 2);
  await assert.rejects(publish(await save(A, doc, null, null, original)), /substituída/);
  await actor(A);
  assert.equal((await db.query('select km,plan_id from public.atlas_activity_records')).rows[0].plan_id, original);
  await db.query("update public.atlas_activity_records set km=3.5 where plan_id=$1", [original]);
  await assert.rejects(db.query("insert into public.atlas_activity_records(user_id,plan_id,session_id,status) values($1,$2,'sessao-002','feito')", [A, original]), /row-level security/);
  await assert.rejects(db.query('update public.atlas_activity_records set plan_id=$1', [newPlan]), /imutável/);
  await actor(C); await db.query('select public.atlas_archive_plan($1)', [newPlan]);
  assert.equal((await db.query('select * from public.atlas_plan_events')).rows.length, 4);
  await actor(OWNER); await db.query('update public.atlas_coach_athletes set active=false where coach_id=$1', [C]);
  await actor(C); assert.equal((await db.query('select * from public.atlas_plans')).rows.length, 0); await assert.rejects(save(A), /não autorizado/);
  await actor(OWNER); await db.query('update public.atlas_coach_athletes set active=true where coach_id=$1', [C]); await db.query('update public.atlas_coaches set active=false where user_id=$1', [C]);
  await actor(C); assert.equal((await db.query('select public.atlas_access_context() as c')).rows[0].c.active, false); await assert.rejects(save(A), /não autorizado/);
  await actor(null, 'anon'); await assert.rejects(db.query('select * from public.atlas_plan_drafts'), /permission denied/); await assert.rejects(publish(draft), /permission denied/);
 } finally {await db.close();}
});
